[project]
name = "cnfutures-session-timeline"
version = "2026.9.19"
description = "获取中国期货交易区间历史，任意天，任意品种"
readme = "README.md"
authors = [
    { name = "myuan", email = "provefars@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
cnfutures-session-timeline = "cnfutures_session_timeline:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
